const mongoose = require("mongoose")

// Define Mongoose Schema
const formSchema = new mongoose.Schema(
  {
    surname: String,
    otherNames: String,
    age: String,
    dob: String,
    sex: String,
    nationality: String,
    state: String,
    maritalStatus: String,
    faculty: String,
    matricNo: String,
    jambRegNo: String,
    department: String,
    telNo: String,
    religion: String,
    nextOfKinName: String,
    relationship: String,
    nextOfKinAddress: String,
    nextOfKinTel: String,
    tuberculosisYes: Boolean,
    tuberculosisNo: Boolean,
    asthmaYes: Boolean,
    asthmaNo: Boolean,
    pepticUlcerYes: Boolean,
    pepticUlcerNo: Boolean,
    sickleCellYes: Boolean,
    sickleCellNo: Boolean,
    allergiesYes: Boolean,
    allergiesNo: Boolean,
    diabetesYes: Boolean,
    diabetesNo: Boolean,
    hypertensionYes: Boolean,
    hypertensionNo: Boolean,
    seizuresYes: Boolean,
    seizuresNo: Boolean,
    mentalIllnessYes: Boolean,
    mentalIllnessNo: Boolean,
    familyTuberculosisYes: Boolean,
    familyTuberculosisNo: Boolean,
    familyMentalIllnessYes: Boolean,
    familyMentalIllnessNo: Boolean,
    familyDiabetesYes: Boolean,
    familyDiabetesNo: Boolean,
    familyHeartDiseaseYes: Boolean,
    familyHeartDiseaseNo: Boolean,
    smallpoxYes: Boolean,
    smallpoxNo: Boolean,
    poliomyelitisYes: Boolean,
    poliomyelitisNo: Boolean,
    immunizationTuberculosisYes: Boolean,
    immunizationTuberculosisNo: Boolean,
    meningitisYes: Boolean,
    meningitisNo: Boolean,
    hpvYes: Boolean,
    hpvNo: Boolean,
    hepatitisBYes: Boolean,
    hepatitisBNo: Boolean,
    tobaccoUseYes: Boolean,
    tobaccoUseNo: Boolean,
    secondhandSmokeYes: Boolean,
    secondhandSmokeNo: Boolean,
    alcoholConsumptionYes: Boolean,
    alcoholConsumptionNo: Boolean,
    tobaccoAlcoholDetails: String,
    otherMedicalInfo: String,
  },
  { timestamps: true }
);

const Form = mongoose.model("Form", formSchema);

module.exports = Form